version: "3.8"

services:
  redis:
    image: redis
    container_name: redis_container
    environment:
      - ALLOW_EMPTY_PASSWORD-yes
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis_container_1
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  services:
    container_name: backend
    build:
      context: ./
    environment:
      REDIS_URL: redis:6379
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 1000
    ports:
      - 5000:5000
    volumes:
      - ./:/var/app
    depends_on:
      - redis
